import os
from pathlib import Path
from dotenv import load_dotenv, set_key
from getpass import getpass, GetPassWarning
import warnings

ENV_FILE = Path(".env")

def mask(s: str, show_last: int = 4) -> str:
    if not s:
        return "<empty>"
    return "*" * max(0, len(s) - show_last) + s[-show_last:]

def ensure_env_loaded():
    if not ENV_FILE.exists():
        ENV_FILE.write_text("# Auto-generated by 01_setup_keys.py\n")
    load_dotenv(dotenv_path=ENV_FILE)

def get_env(key: str) -> str:
    ensure_env_loaded()
    return os.environ.get(key, "").strip()

def set_env(key: str, value: str):
    value = value.strip()
    set_key(str(ENV_FILE), key, value)
    os.environ[key] = value

def prompt_secret(label: str) -> str:
    """
    Securely prompt for a secret without echoing characters.
    Works in terminals, most IDE terminals, and Jupyter/Colab.
    """
    # Suppress noisy warnings in notebook environments.
    with warnings.catch_warnings():
        warnings.simplefilter("ignore", category=GetPassWarning)
        val = getpass(f"{label}\n> ")
    return val.strip()

def configure(print_masked: bool = True):
    ensure_env_loaded()

    # REQUIRED: Portkey API key
    if not get_env("PORTKEY_API_KEY"):
        val = prompt_secret("Enter your Portkey API Key (required):")
        if not val:
            raise ValueError("PORTKEY_API_KEY is required.")
        set_env("PORTKEY_API_KEY", val)
        if print_masked:
            print(f"Saved PORTKEY_API_KEY: {mask(val)}")
    else:
        if print_masked:
            print(f"PORTKEY_API_KEY already set: {mask(get_env('PORTKEY_API_KEY'))}")

    # REQUIRED: Google Gemini API key
    if not get_env("GOOGLE_API_KEY"):
        val = prompt_secret("Enter your Google Gemini API Key (required):")
        if not val:
            raise ValueError("GOOGLE_API_KEY is required.")
        set_env("GOOGLE_API_KEY", val)
        if print_masked:
            print(f"Saved GOOGLE_API_KEY: {mask(val)}")
    else:
        if print_masked:
            print(f"GOOGLE_API_KEY already set: {mask(get_env('GOOGLE_API_KEY'))}")

    # Local Qdrant path (persistent in Colab)
    if not get_env("QDRANT_PATH"):
        set_env("QDRANT_PATH", "/content/qdrant")
        print("Set QDRANT_PATH to /content/qdrant")
    else:
        print(f"QDRANT_PATH: {get_env('QDRANT_PATH')}")

    print("\n✅ Environment ready. Launch the app with: python rag_qdrant_langgraph.py")

if __name__ == "__main__":
    configure()
